name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 15 * *'

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npx --package mini-cross@0.15.2 mc --no-tty _ mvn clean install

